site_name: "Create Backend Plugin Template"
site_description: "User documentation for creating a back-end plugin"

nav:
  - Introduction: index.md
  - Understand And Extend Your Plugin: features/extend.md
  - Handle Authentication and Authorization: features/auth_rbac.md
  - Export Your Plugin to Red Hat Developer Hub: features/export_to_rhdh.md
plugins:
  - techdocs-core